server:
  port: 8082   # choose a unique port different from project-service

spring:
  application:
    name: issue-service

  datasource:
    url: jdbc:mysql://localhost:3306/issue_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
